-- create github_crawler;
-- use github_crawler;
-- create table project_table(
--     name varchar (64),
--     url varchar (1024),
--     description varchar (1024),
--
--     starCnt int,
--     forkCnt int,
--     issueCnt int,
--     date varchar (128)
-- )